version: '3'
volumes:
  postgres_data:
      driver: local
services:
  postgres:
      container_name: kc-db
      image: postgres
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:21.1.1
      restart: unless-stopped
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: gavin
        KEYCLOAK_ADMIN_PASSWORD: belson
      ports:
        - 5365:8080
      command: start-dev
      depends_on:
        - postgres