name: frontend-build
on:
  pull_request:
    paths:
      - 'frontend/**'

  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Set the desired Node.js version here
      - name: Install frontend dependencies
        run: npm install --include=dev
        working-directory: frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend
      - name: Run unit tests
        run: npm test
        working-directory: frontend

